[package]
name = "turbocommit"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.0.0"
inquire = "0.6.0"
reqwest = { version = "0.11.14", features = ["blocking"] }
serde = { version = "1.0.152", features = ["derive"]}
serde_json = "1.0.93"
tiktoken-rs = "0.1.4"
tokenizers = "0.13.2"
